version: '3.9'

services:
  gcloud:
    image: google/cloud-sdk
    volumes:
      - gcp-creds:/creds
      - .:/app
    working_dir: /app
    environment:
      - CLOUDSDK_CONFIG=/creds
      - DATASTORE_EMULATOR_HOST=datastore:8001
      - DATASTORE_PROJECT_ID=local-dev
      - GOOGLE_CLOUD_PROJECT=local-dev
    depends_on:
      - datastore

  datastore:
    build:
      context: ./docker/datastore
    volumes:
      - ./data:/data
    environment:
      - DATASTORE_PROJECT_ID=local-dev

volumes:
  gcp-creds:
